### ISSUE TITLE
生成的 config.yaml 无法使用

### ISSUE THREAD

**Issue by cgcel** [icpd/subscribe2clash#36]
在 proxies 下 alterId 排版不对

cfw 下载的 config.yaml 格式:

```yaml
proxies:
    - { name: '🇭🇰 香港HKT|免流|01', type: vmess, server: foo.com, port: 80, uuid: 0404ab19-5e50-4463-bff9-13076f069b36, alterId: 0, cipher: auto, udp: true, network: ws, ws-opts: { path:bar.mp4, headers: { Host: foo.com } }, ws-path: bar.mp4, ws-headers: { Host: xxx.com } }
```

subscribe2clash 生成的 config.yaml 内格式:

```yaml
proxies:
  - name: "5"
    password: ""
    port: null
    server: ""
    type: ""
  - alterId: "0"
    cipher: none
    name: "\U0001F1ED\U0001F1F0 香港HKT|免流|01"
    network: ws
    port: "80"
    server: foo.com
    type: vmess
    uuid: 0404ab19-5e50-4463-bff9-13076f069b36
    ws-opts:
      path: bar.mp4
```

请问这种情况要如何解决?
